databases:
  - name: jewelryshop
    plan: free
    databaseName: batz
    user: batz_user

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgres://batz_user:lujZSPLSYtnP1X1VXFsV6OROdbmjtRdp@dpg-cnncvkv79t8c739hsci0-a.oregon-postgres.render.com/batz
        fromDatabase:
          name: batz
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4